# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_slot',
            field=models.CharField(default='morning', max_length=200),
            preserve_default=False,
        ),
    ]
