# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160808_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegitUser',
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 8, 15, 24, 8, 448420)),
        ),
    ]
