# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160808_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 9, 15, 10, 16, 260559)),
        ),
    ]
