# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160809_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 9, 15, 11, 40, 53028)),
        ),
    ]
